single_source: 1 
# if video is from single source single_source: 1 and fill same source path for both Cameras 

# fill numeral values if direct cameras are used instead of videos like camera0: 1 

#single_source: 0 
#camera0: /home/ramesh/Vicky/stereo_vision/new_camera_data/stereo_camera_test_230208/80cm/left.avi
#camera1: /home/ramesh/Vicky/stereo_vision/new_camera_data/stereo_camera_test_230208/80cm/right.avi

#single_source: 1 
camera0: /home/ramesh/Vicky/stereo_vision/new_camera_data/stereo_camera_test_230208/80cm/stereo_80cm_checker_Board_230208_0218pm.avi
camera1: /home/ramesh/Vicky/stereo_vision/new_camera_data/stereo_camera_test_230208/80cm/stereo_80cm_checker_Board_230208_0218pm.avi

#camera0: 0
#camera1: 1
frame_width: 1280
frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 5
checkerboard_rows: 4
checkerboard_columns: 7